import eslintCommentsPlugin from '@eslint-community/eslint-plugin-eslint-comments'
import vitest from '@vitest/eslint-plugin'
import prettierConfig from 'eslint-config-prettier'
import importPlugin from 'eslint-plugin-import'
import nPlugin from 'eslint-plugin-n'
import promisePlugin from 'eslint-plugin-promise'
import { parser, plugin as typescriptEslintPlugin } from 'typescript-eslint'

export default [
  {
    ignores: [
      'public/',
      'pnpm-lock.yaml',
      'node_modules/',
      'api/types/foursquare-api.d.ts',
    ],
  },
  {
    files: ['**/*.ts', '**/*.tsx'],
    linterOptions: {
      reportUnusedDisableDirectives: 'error',
    },
    languageOptions: {
      parser,
      parserOptions: {
        projectService: true,
      },
    },
    plugins: {
      '@typescript-eslint': typescriptEslintPlugin,
      '@eslint-community/eslint-comments': eslintCommentsPlugin,
      import: importPlugin,
      n: nPlugin,
      promise: promisePlugin,
    },
    rules: {
      // ── ESLint core rules ──────────────────────────────────────────────
      'accessor-pairs': [
        'error',
        {
          setWithoutGet: true,
          getWithoutSet: false,
          enforceForClassMembers: true,
        },
      ],
      'array-callback-return': [
        'error',
        {
          allowImplicit: false,
          allowVoid: false,
          checkForEach: false,
        },
      ],
      'arrow-body-style': ['error', 'as-needed', { requireReturnForObjectLiteral: false }],
      complexity: 'off',
      'consistent-this': ['error', 'that'],
      'constructor-super': ['error'],
      curly: ['error', 'multi-line'],
      'default-case-last': ['error'],
      eqeqeq: ['error', 'always', { null: 'ignore' }],
      'for-direction': ['error'],
      'grouped-accessor-pairs': ['error', 'getBeforeSet'],
      'guard-for-in': ['error'],
      'logical-assignment-operators': ['error', 'always', { enforceForIfStatements: true }],
      'max-depth': ['error', { max: 5 }],
      'max-lines': 'off',
      'max-nested-callbacks': ['error', { max: 3 }],
      'new-cap': ['error', { newIsCap: true, capIsNew: false, properties: true }],
      'no-alert': ['error'],
      'no-async-promise-executor': ['error'],
      'no-caller': ['error'],
      'no-case-declarations': ['error'],
      'no-class-assign': ['error'],
      'no-compare-neg-zero': ['error'],
      'no-cond-assign': ['error'],
      'no-console': ['error'],
      'no-const-assign': ['error'],
      'no-constant-binary-expression': ['error'],
      'no-constant-condition': ['error', { checkLoops: false }],
      'no-constructor-return': ['error'],
      'no-control-regex': ['error'],
      'no-debugger': ['error'],
      'no-delete-var': ['error'],
      'no-dupe-args': ['error'],
      'no-dupe-else-if': ['error'],
      'no-dupe-keys': ['error'],
      'no-duplicate-case': ['error'],
      'no-empty': ['error', { allowEmptyCatch: true }],
      'no-empty-character-class': ['error'],
      'no-empty-pattern': ['error'],
      'no-empty-static-block': ['error'],
      'no-eval': ['error'],
      'no-ex-assign': ['error'],
      'no-extend-native': ['error'],
      'no-extra-bind': ['error'],
      'no-extra-boolean-cast': ['error'],
      'no-fallthrough': ['error'],
      'no-func-assign': ['error'],
      'no-global-assign': ['error'],
      'no-implicit-globals': ['error'],
      'no-import-assign': ['error'],
      'no-invalid-regexp': ['error'],
      'no-irregular-whitespace': ['error'],
      'no-iterator': ['error'],
      'no-labels': ['error', { allowLoop: false, allowSwitch: false }],
      'no-lone-blocks': ['error'],
      'no-lonely-if': ['error'],
      'no-loss-of-precision': ['error'],
      'no-misleading-character-class': ['error'],
      'no-multi-assign': ['error', { ignoreNonDeclaration: false }],
      'no-multi-str': ['error'],
      'no-negated-condition': 'off',
      'no-new': ['error'],
      'no-new-func': ['error'],
      'no-new-native-nonconstructor': ['error'],
      'no-new-wrappers': ['error'],
      'no-nonoctal-decimal-escape': ['error'],
      'no-obj-calls': ['error'],
      'no-object-constructor': ['error'],
      'no-octal': ['error'],
      'no-octal-escape': ['error'],
      'no-param-reassign': [
        'error',
        {
          props: true,
          ignorePropertyModificationsFor: ['acc'], // Array reduce accumulator
        },
      ],
      'no-plusplus': 'off',
      'no-promise-executor-return': ['error', { allowVoid: false }],
      'no-proto': ['error'],
      'no-prototype-builtins': ['error'],
      'no-regex-spaces': ['error'],
      'no-return-assign': ['error', 'except-parens'],
      'no-script-url': ['error'],
      'no-self-assign': ['error', { props: true }],
      'no-self-compare': ['error'],
      'no-sequences': ['error'],
      'no-shadow-restricted-names': ['error'],
      'no-sparse-arrays': ['error'],
      'no-template-curly-in-string': ['error'],
      'no-this-before-super': ['error'],
      'no-unexpected-multiline': ['error'],
      'no-unmodified-loop-condition': ['error'],
      'no-unneeded-ternary': ['error', { defaultAssignment: false }],
      'no-unreachable': ['error'],
      'no-unreachable-loop': ['error'],
      'no-unsafe-finally': ['error'],
      'no-unsafe-negation': ['error'],
      'no-useless-backreference': ['error'],
      'no-useless-call': ['error'],
      'no-useless-catch': ['error'],
      'no-useless-computed-key': ['error'],
      'no-useless-escape': ['error'],
      'no-useless-rename': ['error'],
      'no-useless-return': ['error'],
      'no-var': ['error'],
      'no-void': ['error', { allowAsStatement: true }],
      'no-with': ['error'],
      'object-shorthand': ['warn', 'properties'],
      'one-var': ['error', { initialized: 'never' }],
      'prefer-const': ['error', { destructuring: 'all', ignoreReadBeforeAssign: false }],
      'prefer-regex-literals': ['error', { disallowRedundantWrapping: true }],
      'prefer-spread': ['error'],
      'preserve-caught-error': 'off',
      radix: 'off',
      strict: ['error', 'safe'],
      'symbol-description': ['error'],
      'unicode-bom': ['error', 'never'],
      'use-isnan': [
        'error',
        {
          enforceForSwitchCase: true,
          enforceForIndexOf: true,
        },
      ],
      'valid-typeof': ['error', { requireStringLiterals: true }],
      yoda: ['error', 'never'],

      // ── @typescript-eslint rules ───────────────────────────────────────
      '@typescript-eslint/adjacent-overload-signatures': ['error'],
      '@typescript-eslint/array-type': 'off',
      '@typescript-eslint/await-thenable': ['error'],
      '@typescript-eslint/ban-ts-comment': [
        'error',
        {
          'ts-expect-error': 'allow-with-description',
          'ts-ignore': true,
          'ts-nocheck': true,
          'ts-check': false,
          minimumDescriptionLength: 3,
        },
      ],
      '@typescript-eslint/ban-tslint-comment': ['error'],
      '@typescript-eslint/class-literal-property-style': ['error', 'fields'],
      '@typescript-eslint/class-methods-use-this': 'off',
      '@typescript-eslint/consistent-generic-constructors': ['error', 'constructor'],
      '@typescript-eslint/consistent-indexed-object-style': ['error', 'record'],
      '@typescript-eslint/consistent-type-assertions': 'warn',
      '@typescript-eslint/consistent-type-definitions': ['error', 'interface'],
      '@typescript-eslint/consistent-type-exports': [
        'error',
        {
          fixMixedExportsWithInlineTypeSpecifier: true,
        },
      ],
      '@typescript-eslint/consistent-type-imports': [
        'error',
        {
          prefer: 'type-imports',
          disallowTypeAnnotations: true,
          fixStyle: 'inline-type-imports',
        },
      ],
      '@typescript-eslint/dot-notation': [
        'error',
        {
          allowIndexSignaturePropertyAccess: false,
          allowKeywords: true,
          allowPattern: '',
          allowPrivateClassPropertyAccess: false,
          allowProtectedClassPropertyAccess: false,
        },
      ],
      '@typescript-eslint/explicit-function-return-type': 'off',
      '@typescript-eslint/init-declarations': 'off',
      '@typescript-eslint/max-params': ['warn', { max: 4 }],
      '@typescript-eslint/method-signature-style': ['error'],
      '@typescript-eslint/naming-convention': 'off',
      '@typescript-eslint/no-array-constructor': ['error'],
      '@typescript-eslint/no-array-delete': ['error'],
      '@typescript-eslint/no-base-to-string': ['error'],
      '@typescript-eslint/no-confusing-non-null-assertion': ['error'],
      '@typescript-eslint/no-confusing-void-expression': [
        'error',
        { ignoreArrowShorthand: false, ignoreVoidOperator: false },
      ],
      '@typescript-eslint/no-deprecated': ['warn'],
      '@typescript-eslint/no-dupe-class-members': ['error'],
      '@typescript-eslint/no-duplicate-enum-values': ['error'],
      '@typescript-eslint/no-duplicate-type-constituents': [
        'error',
        { ignoreIntersections: false, ignoreUnions: false },
      ],
      '@typescript-eslint/no-dynamic-delete': ['error'],
      '@typescript-eslint/no-empty-function': [
        'error',
        {
          allow: [],
        },
      ],
      '@typescript-eslint/no-empty-object-type': 'off',
      '@typescript-eslint/no-explicit-any': ['error', { fixToUnknown: false, ignoreRestArgs: false }],
      '@typescript-eslint/no-extra-non-null-assertion': ['error'],
      '@typescript-eslint/no-extraneous-class': ['error', { allowWithDecorator: true }],
      '@typescript-eslint/no-floating-promises': ['error'],
      '@typescript-eslint/no-for-in-array': ['error'],
      '@typescript-eslint/no-implied-eval': ['error'],
      '@typescript-eslint/no-import-type-side-effects': ['error'],
      '@typescript-eslint/no-inferrable-types': [
        'error',
        { ignoreParameters: false, ignoreProperties: false },
      ],
      '@typescript-eslint/no-invalid-void-type': ['error'],
      '@typescript-eslint/no-loop-func': ['error'],
      '@typescript-eslint/no-magic-numbers': 'off',
      '@typescript-eslint/no-meaningless-void-operator': ['error', { checkNever: true }],
      '@typescript-eslint/no-misused-new': ['error'],
      '@typescript-eslint/no-misused-promises': ['error'],
      '@typescript-eslint/no-misused-spread': ['error', { allow: [] }],
      '@typescript-eslint/no-mixed-enums': ['error'],
      '@typescript-eslint/no-namespace': 'off',
      '@typescript-eslint/no-non-null-asserted-nullish-coalescing': ['error'],
      '@typescript-eslint/no-non-null-asserted-optional-chain': ['error'],
      '@typescript-eslint/no-non-null-assertion': ['error'],
      '@typescript-eslint/no-redundant-type-constituents': ['error'],
      '@typescript-eslint/no-require-imports': ['error', { allow: [], allowAsImport: false }],
      '@typescript-eslint/no-this-alias': ['error', { allowDestructuring: true }],
      '@typescript-eslint/no-unnecessary-boolean-literal-compare': ['error'],
      '@typescript-eslint/no-unnecessary-condition': [
        'error',
        {
          allowConstantLoopConditions: true,
        },
      ],
      '@typescript-eslint/no-unnecessary-parameter-property-assignment': ['error'],
      '@typescript-eslint/no-unnecessary-qualifier': ['error'],
      '@typescript-eslint/no-unnecessary-template-expression': ['error'],
      '@typescript-eslint/no-unnecessary-type-arguments': ['error'],
      '@typescript-eslint/no-unnecessary-type-assertion': ['error'],
      '@typescript-eslint/no-unnecessary-type-constraint': ['error'],
      '@typescript-eslint/no-unnecessary-type-conversion': ['error'],
      '@typescript-eslint/no-unnecessary-type-parameters': ['error'],
      '@typescript-eslint/no-unsafe-argument': ['error'],
      '@typescript-eslint/no-unsafe-assignment': ['error'],
      '@typescript-eslint/no-unsafe-call': ['error'],
      '@typescript-eslint/no-unsafe-declaration-merging': ['error'],
      '@typescript-eslint/no-unsafe-enum-comparison': ['error'],
      '@typescript-eslint/no-unsafe-function-type': ['error'],
      '@typescript-eslint/no-unsafe-member-access': ['error'],
      '@typescript-eslint/no-unsafe-return': ['error'],
      '@typescript-eslint/no-unsafe-type-assertion': ['error'],
      '@typescript-eslint/no-unsafe-unary-minus': ['error'],
      '@typescript-eslint/no-unused-expressions': [
        'error',
        {
          allowShortCircuit: true,
          allowTernary: true,
          allowTaggedTemplates: true,
          enforceForJSX: false,
        },
      ],
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
        },
      ],
      '@typescript-eslint/no-use-before-define': [
        'error',
        {
          functions: false,
          classes: false,
          enums: false,
          variables: false,
          typedefs: false,
        },
      ],
      '@typescript-eslint/no-useless-constructor': ['error'],
      '@typescript-eslint/no-useless-empty-export': ['error'],
      '@typescript-eslint/no-wrapper-object-types': ['error'],
      '@typescript-eslint/non-nullable-type-assertion-style': ['error'],
      '@typescript-eslint/only-throw-error': 'off',
      '@typescript-eslint/prefer-as-const': ['error'],
      '@typescript-eslint/prefer-destructuring': 'off',
      '@typescript-eslint/prefer-find': ['error'],
      '@typescript-eslint/prefer-for-of': ['error'],
      '@typescript-eslint/prefer-function-type': ['error'],
      '@typescript-eslint/prefer-includes': ['error'],
      '@typescript-eslint/prefer-literal-enum-member': ['error', { allowBitwiseExpressions: true }],
      '@typescript-eslint/prefer-namespace-keyword': ['error'],
      '@typescript-eslint/prefer-nullish-coalescing': [
        'error',
        {
          ignoreConditionalTests: false,
          ignoreMixedLogicalExpressions: false,
        },
      ],
      '@typescript-eslint/prefer-optional-chain': ['error'],
      '@typescript-eslint/prefer-promise-reject-errors': ['error'],
      '@typescript-eslint/prefer-readonly': ['error'],
      '@typescript-eslint/prefer-reduce-type-parameter': ['error'],
      '@typescript-eslint/prefer-regexp-exec': ['error'],
      '@typescript-eslint/prefer-return-this-type': ['error'],
      '@typescript-eslint/prefer-string-starts-ends-with': [
        'error',
        { allowSingleElementEquality: 'never' },
      ],
      '@typescript-eslint/promise-function-async': ['error'],
      '@typescript-eslint/related-getter-setter-pairs': ['error'],
      '@typescript-eslint/require-array-sort-compare': ['error', { ignoreStringArrays: true }],
      '@typescript-eslint/require-await': ['error'],
      '@typescript-eslint/restrict-plus-operands': ['error', { skipCompoundAssignments: false }],
      '@typescript-eslint/restrict-template-expressions': 'off',
      '@typescript-eslint/return-await': ['error', 'always'],
      '@typescript-eslint/strict-boolean-expressions': 'off',
      '@typescript-eslint/switch-exhaustiveness-check': [
        'error',
        {
          allowDefaultCaseForExhaustiveSwitch: false,
          requireDefaultForNonUnion: false,
          considerDefaultExhaustiveForUnions: true,
        },
      ],
      '@typescript-eslint/triple-slash-reference': [
        'error',
        { lib: 'never', path: 'never', types: 'never' },
      ],
      '@typescript-eslint/unbound-method': ['error', { ignoreStatic: false }],
      '@typescript-eslint/unified-signatures': [
        'error',
        { ignoreDifferentlyNamedParameters: false },
      ],
      '@typescript-eslint/use-unknown-in-catch-callback-variable': ['error'],

      // ── eslint-plugin-eslint-comments rules ────────────────────────────
      '@eslint-community/eslint-comments/disable-enable-pair': [
        'error',
        { allowWholeFile: true },
      ],
      '@eslint-community/eslint-comments/no-aggregating-enable': ['error'],
      '@eslint-community/eslint-comments/no-duplicate-disable': ['error'],
      '@eslint-community/eslint-comments/no-unlimited-disable': ['error'],
      '@eslint-community/eslint-comments/no-unused-enable': ['error'],
      '@eslint-community/eslint-comments/require-description': [
        'error',
        {
          ignore: ['eslint-enable', 'eslint-env'],
        },
      ],

      // ── eslint-plugin-n rules ──────────────────────────────────────────
      'n/handle-callback-err': ['error', '^(err|error)$'],
      'n/no-callback-literal': ['error'],
      'n/no-deprecated-api': ['error'],
      'n/no-exports-assign': ['error'],
      'n/no-new-require': ['error'],
      'n/no-path-concat': ['error'],
      'n/process-exit-as-throw': ['error'],

      // ── eslint-plugin-promise rules ────────────────────────────────────
      'promise/avoid-new': 'off',
      'promise/param-names': ['error'],

      // ── eslint-plugin-import rules ─────────────────────────────────────
      'import/enforce-node-protocol-usage': ['error', 'always'],
      'import/export': ['error'],
      'import/first': ['error'],
      'import/no-absolute-path': ['error', { esmodule: true, commonjs: true, amd: false }],
      'import/no-duplicates': ['error'],
      'import/no-named-default': ['error'],
      'import/no-webpack-loader-syntax': ['error'],
    },
  },
  {
    files: ['**/__tests__/**', '**/__integration__/**', '**/*.test.ts'],
    plugins: {
      vitest,
    },
    rules: {
      ...vitest.configs.recommended.rules,
      'vitest/prefer-called-exactly-once-with': 'off',
      '@typescript-eslint/no-unsafe-type-assertion': 'off',
      '@typescript-eslint/no-unsafe-assignment': 'off',
      '@typescript-eslint/no-unsafe-member-access': 'off',
      '@typescript-eslint/no-unsafe-call': 'off',
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-unnecessary-type-assertion': 'off',
      '@typescript-eslint/no-non-null-assertion': 'off',
      '@typescript-eslint/unbound-method': 'off',
      'max-nested-callbacks': 'off',
    },
  },
  prettierConfig,
]
